apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - image: moamenmohasseb/reverseproxy:v7
        name: udagram-reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2024Mi"
            cpu: "800m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always